# Step 1: Use official OpenJDK runtime as base image
FROM openjdk:17-jdk-slim

# Step 2: Set working directory inside container
WORKDIR /app

# Step 3: Copy the packaged JAR from the target directory
# Make sure the JAR name matches the one generated by Maven
COPY target/*.jar app.jar

# Step 4: Expose the port your app listens on
EXPOSE 8080

# Step 5: Command to run the JAR
# Non-interactive version keeps the pod alive
ENTRYPOINT ["java", "-jar", "app.jar"]
